jobs:
  check:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Get Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./action/action

name: Run

on:
  schedule:
    - cron: "15 2/3 * * *"
